FROM node
#FROM node:16

# Create app directory
WORKDIR /src/app/

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
#COPY package*.json ./
COPY package.json /src/app


#test esnasında ci kullanalım
#RUN npm ci
RUN npm install
#RUN npm set registry=https://registry.npmjs.org/
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
#COPY . .
COPY . /src/app

EXPOSE 8083
# CMD [ "node", "server.js" ]
# CMD [ "npm", "start" ]
CMD [ "npm", "run", "live" ]